### PR TITLE
Add "Join" page

### PR DESCRIPTION
**Pull request by briangershon**
- [x] Adds new "Join" page at `/join`
- [ ] Needs someone with CMS access to add a "Join" link the "Useful Links" section in the footer that points to this page

Screenshot 2023-02-17 at 10 08 19 AM

### CODE REVIEW

**Comment by kempsterrrr** [comment]
Thanks for the PR, @briangershon 🤝 

Sadly, the [Wiki Page](https://developerdao.notion.site/Getting-Started-with-Developer-DAO-2bddd332c51a4957b0b83f60f9fa4ebe#740ebdd2dc5d4a7a9ae69747f4be5c54) you've linked is very out of date (not your fault obv) still talks about guilds, lists channels that are no longer needed and other bits as well.

A link to join the DAO on the home page already (see image below) takes folks to our [Guild Profiile](https://guild.xyz/dd), where they can authenticate to join the server. That page isn't as informative as a Wiki, which clearly needs updating, but it does list the requirements to join (see second image).

Guess that means merging this doesn't make sense. A couple of questions:

1) Is sharing the link to your guild page directly with folks enough? - https://guild.xyz/dd
2) If not, is sending them to the home page and asking them to click the "Join" button in the first image below OK?

_Guld page could do with a little more detail as well._

image
Developer DAO

**Comment by briangershon** [comment]
Thanks @kempsterrrr 

I think the new page could still be valuable:

- we can point people to our branded site `https://developerdao.com/join` instead of sending them to guild.xyz.
- we could add a bit of welcome/introductory text on Join that does ultimately tell them to head over to guild.xyz -- I agree Notion isn't the best destination (especially if out of date).
- Then on home page change the Join Discord button on home page to "Join the DAO" -- takes 'em to Join and they they can click guild.xyz

So sort of the best of both worlds -- and easy and branded developerdao.com link to put on sites -- and users don't have to start on guild.xyz albeit ultimately end up there as before.

I did see Join Discord -- but I wasn't sure this was the best place to send people initially since they need to have $CODE/NFT to get it. Albeit with the new Discord changes, and details on guild.xyz, maybe all ok.

---

Or if we do just want to keep what we have today, on eternal site I could just say go visit developerdao.com -> and look for the Join Discord -- which is what you suggest as option #2. That works too.

Or yeah, adding a nice intro at the top of guild.xyz.

**Comment by briangershon** [comment]
Resolution: The main path for Joining DD is directing people to the Discord button on home page, and that has a list of requirements for joining.

Closing PR. Can always open again if need to have a `/join` link presents itself.

cc: @kempsterrrr

**Comment by kempsterrrr** [comment]
@briangershon, thanks for letting me know. There is an updated design that has started to be implemented [here](https://www.figma.com/file/TbHSqru2o5UHvoT1lBX2Xr/Untitled?node-id=0%3A1&t=xIaH8yEP9l9H7ty8-1)

**Pull request closed without merging**
