### PR TITLE
feat(home): Implement Home page

### PR DESCRIPTION
**Pull request by andriishupta**
### What does it do?
Initial implementation of Home Page

### Any helpful background information?
Changes for v3 of developerdao.com

### Any new dependencies? Why were they added?
A few dependencies were added for dev purposes, such as this is a new project.

### Relevant screenshots/gifs
image
image
image
image
image
image

### CODE REVIEW

**Comment by andriishupta** [comment]
Some challenges that should be addressed:
- design for Light theme
- Mobile menu functionality
- Feather icons don't have full list of icons, so I copied SVGs from Figma, but it is hard to update them from CSS: stroke and fill located in different places svg / path and it is not possible without tricks to center them / change color manually

**Comment by andriishupta** [comment]
@mhmulford0 , I saved the URQL client in the folder during rebase cause we would use it in getServerSideProps on different pages, not only on FrontEnd Provider

**Comment by kempsterrrr** [comment]
Looking great @andriishupta - left some comments on the Vercel preview link. Are you able to see these by clicking the preview deployment?

**Comment by andriishupta** [comment]
Would check and let you know tomorrow

Also, I have "found" "mobile version" way down on Figma - would improve current mobile implementation

**Comment by andriishupta** [comment]
Latest updates:
- improve the mobile view 
- added mobile menu

image

image

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
No idea how to approve this

**Comment by kempsterrrr** [comment]
Sorry for the delayed response here @andriishupta - given your authorised access to Vercel so you can see the comments.

There is a TS build error in the latest push, so I can't see the mobile build in the preview but the approach to the menu looks great to me. Nice work! Assume we'll eventually change the words but it made me LOL 😂 

Leaving a thought here, unsure how I feel about the grey icons - this is a design problem though ofc but interested to get folks thoughts.

**Pull request merged**
